# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import springbootdata_pb2 as springbootdata__pb2


class TestGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.testMethod = channel.unary_unary(
                '/base_package.TestGrpcService/testMethod',
                request_serializer=springbootdata__pb2.TestRequest.SerializeToString,
                response_deserializer=springbootdata__pb2.TestReply.FromString,
                )


class TestGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def testMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'testMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.testMethod,
                    request_deserializer=springbootdata__pb2.TestRequest.FromString,
                    response_serializer=springbootdata__pb2.TestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'base_package.TestGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def testMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.TestGrpcService/testMethod',
            springbootdata__pb2.TestRequest.SerializeToString,
            springbootdata__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
